#################################################################
#    ***      Плагин NoMult "Нет Мультам!"               ***    #
#    ***      Проект: http://wealth-mc.net               ***    #
#################################################################
#
#debug:			вывод сообщений плагина в консоль
#group:			группа для мультиакаунтов
#default:		группа игроков "по умолчанию"
#times:			интервал автосохранения переменных (в секундах) 
#message:		текст сообщения в чат при "залогинивании" игрока на сервере
#message2:		текст сообщения в чат при "разлогинивании" игрока на сервере
#message3:		текст сообщения в чат при "залогинивании" мультиаккаунта
#message4:		текст сообщения в чат при первом заходе игрока на сервер (с момента установки плагина)
#pvp:			включить/отключить защиту от PVP между мультиаккаунтами
#blockjoin:		блокировать сообщение при подключении игрока к серверу и заменить на "message" при залогинивании (true/false)
#blockleave:	блокировать сообщение при отключении игрока от сервера и заменить на "message2" при разлогинивании (true/false)
debug: true
group: newgroup
default: default 
times: 60
message: подключился к серверу!
message2: отключился от сервера!
message3: по результатам проверки является мультиаккаунтом!
message4: впервые зашел на сервер!
pvp: true
blockjoin: true
blockleave: true