#################################################################
#    ***      Плагин NoMult "Нет Мультам!"               ***    #
#    ***      Проект: http://wealth-mc.net               ***    #
#################################################################
#
#debug:			вывод сообщений плагина в консоль
#group:			группа для мультиакаунтов
#default:		группа игроков "по умолчанию"
#times:			интервал автосохранения переменных (в секундах) 
#login:			выводить ли сообщение в чат при "залогинивании" игрока на сервере (true/false) 
#message:		текст сообщения в чат "залогинивании" игрока на сервере
#pvp:			включить/отключить защиту от PVP между мультиаккаунтами
debug: true
group: newgroup
default: default 
times: 60
login: true
message: подключился к серверу!
pvp: true