name: NoMult
main: net.wealth_mc.nomult.NoMult
version: 1.7.1
author: Korvinius
description: No Mults
website: http://wealth-mc.net 
commands:
   nomult:                 
      aliases: [nm, nom]                                                                                                                                                                                                                                                                                                           
      usage: /nomult [args]